In [5]:
import pandas as pd
import numpy as np
import re
df=pd.read_csv('messysupermarket_sales(1).csv')
df

,Sales_ID,Date,Custumer_Name,Product,Category,Quantity,Unit_Price,Total,Payment_Method
0,S1,4th February 2026,Miriam,Cabbage,Vegetable,5,3 USD,15USD,CASH
1,S2,4th February 2026,Miriam,champagne,BEVERAGES,3,NaN,45 USD,CASH
2,S3,4/2/2026,Miriam,NaN,FRUITS,1O,$5,150$,CASH
3,S4,4/2/2026,NaN,GRAPES,FRUITS,3,4,12,CASH
4,S5,4/2/2026,Miriam,APPLES,NaN,13,3,39USD,CASH
...,...,...,...,...,...,...,...,...,...
347,O40,28-Feb-26,NaN,potatoes,NaN,2,8,16,bank Transfer
348,O41,28-Feb-26,TYLER,NaN,HOUSEHOLD,4,3.25,NaN,credit card
349,O42,28-Feb-26,PaIgE BriGGS,sausage,PERSONAL Care,2,1.5,3,Credit Card
350,O43,28-Feb-26,TraviS saMS,rice,NaN,1O,0,0,payPAL
351,O44,28-Feb-26,NaN,NaN,Fruits,1,usd3.25,13.25,NaN

In [6]:
df.isnull().sum()

Sales_ID           0
Date              37
Custumer_Name     63
Product           39
Category          75
Quantity          36
Unit_Price        50
Total             60
Payment_Method    58
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 352 entries, 0 to 351
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sales_ID        352 non-null    object
 1   Date            315 non-null    object
 2   Custumer_Name   289 non-null    object
 3   Product         313 non-null    object
 4   Category        277 non-null    object
 5   Quantity        316 non-null    object
 6   Unit_Price      302 non-null    object
 7   Total           292 non-null    object
 8   Payment_Method  294 non-null    object
dtypes: object(9)
memory usage: 24.9+ KB

In [8]:
df.describe()

,Sales_ID,Date,Custumer_Name,Product,Category,Quantity,Unit_Price,Total,Payment_Method
count,352,315,289,313,277,316,302,292,294
unique,340,30,212,163,75,15,61,155,23
top,O2,2/7/2026,Miriam,beer,BAKERY,3,4,0,CASH
freq,2,68,5,11,13,40,27,9,51

In [9]:
text_col=['Custumer_Name','Product','Category','Payment_Method']
for col in text_col:
    if col in df.columns:
        df[col]=df[col].astype('string').str.strip().str.title()
df

,Sales_ID,Date,Custumer_Name,Product,Category,Quantity,Unit_Price,Total,Payment_Method
0,S1,4th February 2026,Miriam,Cabbage,Vegetable,5,3 USD,15USD,Cash
1,S2,4th February 2026,Miriam,Champagne,Beverages,3,NaN,45 USD,Cash
2,S3,4/2/2026,Miriam,<NA>,Fruits,1O,$5,150$,Cash
3,S4,4/2/2026,<NA>,Grapes,Fruits,3,4,12,Cash
4,S5,4/2/2026,Miriam,Apples,<NA>,13,3,39USD,Cash
...,...,...,...,...,...,...,...,...,...
347,O40,28-Feb-26,<NA>,Potatoes,<NA>,2,8,16,Bank Transfer
348,O41,28-Feb-26,Tyler,<NA>,Household,4,3.25,NaN,Credit Card
349,O42,28-Feb-26,Paige Briggs,Sausage,Personal Care,2,1.5,3,Credit Card
350,O43,28-Feb-26,Travis Sams,Rice,<NA>,1O,0,0,Paypal
351,O44,28-Feb-26,<NA>,<NA>,Fruits,1,usd3.25,13.25,<NA>

In [10]:
for col in ['Custumer_Name']:
    if col in df.columns:
        df[col]=df[col].replace(['nan',''],np.nan).fillna('name')
df

,Sales_ID,Date,Custumer_Name,Product,Category,Quantity,Unit_Price,Total,Payment_Method
0,S1,4th February 2026,Miriam,Cabbage,Vegetable,5,3 USD,15USD,Cash
1,S2,4th February 2026,Miriam,Champagne,Beverages,3,NaN,45 USD,Cash
2,S3,4/2/2026,Miriam,<NA>,Fruits,1O,$5,150$,Cash
3,S4,4/2/2026,name,Grapes,Fruits,3,4,12,Cash
4,S5,4/2/2026,Miriam,Apples,<NA>,13,3,39USD,Cash
...,...,...,...,...,...,...,...,...,...
347,O40,28-Feb-26,name,Potatoes,<NA>,2,8,16,Bank Transfer
348,O41,28-Feb-26,Tyler,<NA>,Household,4,3.25,NaN,Credit Card
349,O42,28-Feb-26,Paige Briggs,Sausage,Personal Care,2,1.5,3,Credit Card
350,O43,28-Feb-26,Travis Sams,Rice,<NA>,1O,0,0,Paypal
351,O44,28-Feb-26,name,<NA>,Fruits,1,usd3.25,13.25,<NA>

In [11]:
for col in['Category','Product','Payment_Method']:
    if col in df.columns:
        df[col]=df[col].replace(['nan',''],np.nan).fillna('unknown')

In [12]:
df

,Sales_ID,Date,Custumer_Name,Product,Category,Quantity,Unit_Price,Total,Payment_Method
0,S1,4th February 2026,Miriam,Cabbage,Vegetable,5,3 USD,15USD,Cash
1,S2,4th February 2026,Miriam,Champagne,Beverages,3,NaN,45 USD,Cash
2,S3,4/2/2026,Miriam,unknown,Fruits,1O,$5,150$,Cash
3,S4,4/2/2026,name,Grapes,Fruits,3,4,12,Cash
4,S5,4/2/2026,Miriam,Apples,unknown,13,3,39USD,Cash
...,...,...,...,...,...,...,...,...,...
347,O40,28-Feb-26,name,Potatoes,unknown,2,8,16,Bank Transfer
348,O41,28-Feb-26,Tyler,unknown,Household,4,3.25,NaN,Credit Card
349,O42,28-Feb-26,Paige Briggs,Sausage,Personal Care,2,1.5,3,Credit Card
350,O43,28-Feb-26,Travis Sams,Rice,unknown,1O,0,0,Paypal
351,O44,28-Feb-26,name,unknown,Fruits,1,usd3.25,13.25,unknown

In [13]:
df['Quantity']=df['Quantity'].astype(str).str.replace(r'[^\d.]','',regex=True)
df['Quantity']=pd.to_numeric(df['Quantity'],errors='coerce').fillna(0.0)
df['Quantity']

0       5.0
1       3.0
2       1.0
3       3.0
4      13.0
       ...
347     2.0
348     4.0
349     2.0
350     1.0
351     1.0
Name: Quantity, Length: 352, dtype: float64

In [14]:
for col in['Unit_Price','Total']:
    if col in df.columns:
        df[col]=df[col].astype(str).replace(r'[^\d.]','',regex=True)
        df[col]=pd.to_numeric(df[col],errors='coerce').fillna(0.0)

In [15]:
df

,Sales_ID,Date,Custumer_Name,Product,Category,Quantity,Unit_Price,Total,Payment_Method
0,S1,4th February 2026,Miriam,Cabbage,Vegetable,5.0,3.00,15.00,Cash
1,S2,4th February 2026,Miriam,Champagne,Beverages,3.0,0.00,45.00,Cash
2,S3,4/2/2026,Miriam,unknown,Fruits,1.0,5.00,150.00,Cash
3,S4,4/2/2026,name,Grapes,Fruits,3.0,4.00,12.00,Cash
4,S5,4/2/2026,Miriam,Apples,unknown,13.0,3.00,39.00,Cash
...,...,...,...,...,...,...,...,...,...
347,O40,28-Feb-26,name,Potatoes,unknown,2.0,8.00,16.00,Bank Transfer
348,O41,28-Feb-26,Tyler,unknown,Household,4.0,3.25,0.00,Credit Card
349,O42,28-Feb-26,Paige Briggs,Sausage,Personal Care,2.0,1.50,3.00,Credit Card
350,O43,28-Feb-26,Travis Sams,Rice,unknown,1.0,0.00,0.00,Paypal
351,O44,28-Feb-26,name,unknown,Fruits,1.0,3.25,13.25,unknown

In [16]:
df.dropna(subset=['Sales_ID','Custumer_Name'])

,Sales_ID,Date,Custumer_Name,Product,Category,Quantity,Unit_Price,Total,Payment_Method
0,S1,4th February 2026,Miriam,Cabbage,Vegetable,5.0,3.00,15.00,Cash
1,S2,4th February 2026,Miriam,Champagne,Beverages,3.0,0.00,45.00,Cash
2,S3,4/2/2026,Miriam,unknown,Fruits,1.0,5.00,150.00,Cash
3,S4,4/2/2026,name,Grapes,Fruits,3.0,4.00,12.00,Cash
4,S5,4/2/2026,Miriam,Apples,unknown,13.0,3.00,39.00,Cash
...,...,...,...,...,...,...,...,...,...
347,O40,28-Feb-26,name,Potatoes,unknown,2.0,8.00,16.00,Bank Transfer
348,O41,28-Feb-26,Tyler,unknown,Household,4.0,3.25,0.00,Credit Card
349,O42,28-Feb-26,Paige Briggs,Sausage,Personal Care,2.0,1.50,3.00,Credit Card
350,O43,28-Feb-26,Travis Sams,Rice,unknown,1.0,0.00,0.00,Paypal
351,O44,28-Feb-26,name,unknown,Fruits,1.0,3.25,13.25,unknown

In [17]:

def clean_date_string(val):

    if pd.isna(val) or str(val).strip().lower() in ['', 'nan', 'none']:
        return np.nan

    val = str(val).strip().lower()

    # Remove commas
    val = val.replace(",", "")

    # Remove ordinal suffixes
    val = re.sub(r'(\d+)(st|nd|rd|th)', r'\1', val)

    # Correct spelling mistakes
    corrections = {
        "febuary": "february",
        "feburary": "february",
        "febrary": "february",
        "febraray": "february",
        "februaru": "february",
        "o2": "02"
    }

    for wrong, correct in corrections.items():
        val = val.replace(wrong, correct)

    # Replace standalone "fe" with "feb"
    val = re.sub(r'\bfe\b', 'feb', val)

    # Standardize separators
    val = re.sub(r"[.\-\s]", "/", val)

    if re.fullmatch(r"\d{1,2}[/-][a-z]+", val):
        val += "/2026"

    return val

df["Date"] = df["Date"].apply(clean_date_string)

df["Date"] = pd.to_datetime(
    df["Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)
df

,Sales_ID,Date,Custumer_Name,Product,Category,Quantity,Unit_Price,Total,Payment_Method
0,S1,2026-02-04,Miriam,Cabbage,Vegetable,5.0,3.00,15.00,Cash
1,S2,2026-02-04,Miriam,Champagne,Beverages,3.0,0.00,45.00,Cash
2,S3,2026-02-04,Miriam,unknown,Fruits,1.0,5.00,150.00,Cash
3,S4,2026-02-04,name,Grapes,Fruits,3.0,4.00,12.00,Cash
4,S5,2026-02-04,Miriam,Apples,unknown,13.0,3.00,39.00,Cash
...,...,...,...,...,...,...,...,...,...
347,O40,2026-02-28,name,Potatoes,unknown,2.0,8.00,16.00,Bank Transfer
348,O41,2026-02-28,Tyler,unknown,Household,4.0,3.25,0.00,Credit Card
349,O42,2026-02-28,Paige Briggs,Sausage,Personal Care,2.0,1.50,3.00,Credit Card
350,O43,2026-02-28,Travis Sams,Rice,unknown,1.0,0.00,0.00,Paypal
351,O44,2026-02-28,name,unknown,Fruits,1.0,3.25,13.25,unknown

In [18]:
df.tail(15)

,Sales_ID,Date,Custumer_Name,Product,Category,Quantity,Unit_Price,Total,Payment_Method
337,O30,2026-02-24,Nathan,Bread,Groceries,1.0,1.00,1.00,Cash
338,O31,2026-02-24,Ethan Doris,Pepsi,Household,3.0,4.00,0.00,Paypal
339,O32,2026-02-25,Ethan Doris,Grapes,Stationary,3.0,0.00,3.00,unknown
340,O33,2026-02-25,Ethan Doris,Notebook,Frozen,2.0,8.00,16.00,unknown
341,O34,2026-02-27,Samantha Pruitt,Tuna,Diary,50.0,2.00,100.00,unknown
342,O35,2026-02-27,Samantha Pruitt,Eggs,Household,6.0,0.00,6.00,Cash
343,O36,2026-02-27,Samantha Pruitt,Beer,unknown,20.0,0.00,21.00,unknown
344,O37,2026-02-27,Samantha Pruitt,Tea,Alcholic Beverage,3.0,2.50,7.50,Apple Pay
345,O38,2026-02-27,Doris,Lettuce,Personal Care,20.0,4.00,80.00,Csash
346,O39,2026-02-28,Xander Reyes,Yogut,Beverages,2.0,1.00,2.00,Apple Pay
347,O40,2026-02-28,name,Potatoes,unknown,2.0,8.00,16.00,Bank Transfer
348,O41,2026-02-28,Tyler,unknown,Household,4.0,3.25,0.00,Credit Card
349,O42,2026-02-28,Paige Briggs,Sausage,Personal Care,2.0,1.50,3.00,Credit Card
350,O43,2026-02-28,Travis Sams,Rice,unknown,1.0,0.00,0.00,Paypal
351,O44,2026-02-28,name,unknown,Fruits,1.0,3.25,13.25,unknown

In [19]:
df.isnull().sum()

Sales_ID           0
Date              37
Custumer_Name      0
Product            0
Category           0
Quantity           0
Unit_Price         0
Total              0
Payment_Method     0
dtype: int64

In [20]:
df.to_csv('cleaned_supermarket_sales.csv',index=False)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 352 entries, 0 to 351
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sales_ID        352 non-null    object
 1   Date            315 non-null    datetime64[ns]
 2   Custumer_Name   352 non-null    string
 3   Product         352 non-null    string
 4   Category        352 non-null    string
 5   Quantity        352 non-null    float64
 6   Unit_Price      352 non-null    float64
 7   Total           352 non-null    float64
 8   Payment_Method  352 non-null    string
dtypes: datetime64[ns](1), float64(3), object(1), string(4)
memory usage: 24.9+ KB